### ISSUE TITLE
Linking a model with an existing notebook/dataset

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/bioimage-io-models#49]
Hi there!

Is it possible to link a model with an existing notebook/dataset in bioimage.io when those are not part of my repository? For example, a model trained with one of the ZeroCostDL4Mic notebooks.
If so, how should I specify it in the manifest.bioimage.io.yaml?

At the moment we have it as follows when we use our own notebooks (https://github.com/deepimagej/models/blob/master/manifest.bioimage.io.yaml):

````yaml
model:
  - id: UNet2DPancreaticSegmentation
    source: https://raw.githubusercontent.com/deepimagej/models/master/u-net_pancreatic_segmentation/UNet2DPancreaticSegmentation.model.yaml
    download_url: https://github.com/deepimagej/models/releases/download/0.3/u-net_pancreatic_segmentation.zip
    links:
      - unet-pancreaticcellsegmentation
notebook:
  - id: unet-pancreaticcellsegmentation
...
````

Thank you!
